[tools]
deno = "2.7.12"
tombi = "latest"
"aqua:wasm-bindgen/wasm-pack" = "latest"
hk = "latest"
pkl = "latest"
"aqua:betterleaks/betterleaks" = "latest"
hadolint = "latest"
editorconfig-checker = "latest"
rumdl = "latest"
typos = "latest"

[tools.rust]
version = "1.95.0"
components = "rust-analyzer"
targets = "wasm32-unknown-unknown"

[hooks]
enter = "mise outdated --local --silent"
# Automatically install/update hooks when tools are installed
postinstall = "hk install --mise"

[tasks.test]
description = "Run Deno integration tests"
tools.ffmpeg = "latest"
usage = '''
  flag "--update-snapshot" help="Update the visual tests snapshot"
'''
env.TZ = "UTC"
run = "deno test -A -- ${usage_update_snapshot:+--update-snapshot}"
