name: Publish versions

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and publish package
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          cache: false
          install: false
      - run: mise run publish
