name: Publish versions

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and publish package
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          cache: false
      - run: mise run publish
