name: Releases management

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          # Token permissions: read access to metadata, read and write access to
          # actions, code and pull requests.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
