name: Tests and code quality

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'
          skip_after_successful_duplicate: true
  tests:
    name: Code quality and tests
    runs-on: ubuntu-latest
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Get Rust version from dev container Dockerfile
        id: get-rust-version
        run: |
          echo "RUST_VERSION=$(grep -oP 'FROM rust:\K[\d.]+' .devcontainer/Dockerfile)" \
          >> $GITHUB_OUTPUT
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.get-rust-version.outputs.RUST_VERSION }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Lint code with Clippy
        run: cargo clippy -- -D warnings
      - name: Run unit tests
        run: cargo test
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
      - name: Build
        run: wasm-pack build --target web
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: integration/yarn.lock
      - name: Run end-to-end tests 🧪
        uses: cypress-io/github-action@v4
        with:
          command: yarn test:e2e:ci
          working-directory: integration
      - name: Upload Cypress screenshots and videos 🖥️📽️
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            integration/cypress/e2e/__image_snapshots__
            integration/cypress/screenshots
            integration/cypress/videos
