name: Tests and code quality

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'
          skip_after_successful_duplicate: true
  tests:
    name: Code quality and tests
    runs-on: ubuntu-latest
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v5
      - name: Get Rust version from dev container Dockerfile
        id: get-rust-version
        run: |
          echo "RUST_VERSION=$(grep -oP 'FROM rust:\K[\d.]+' .devcontainer/Dockerfile)" \
          >> $GITHUB_OUTPUT
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.get-rust-version.outputs.RUST_VERSION }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Lint code with Clippy
        run: cargo clippy -- -D warnings
      - name: Run unit tests 🧪
        run: cargo test
      - name: Get Deno version from dev container Dockerfile
        id: get-deno-version
        run: |
          echo "DENO_VERSION=$(grep -oP 'FROM denoland/deno:bin-\K[\d.]+' .devcontainer/Dockerfile)" \
          >> $GITHUB_OUTPUT
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ steps.get-deno-version.outputs.DENO_VERSION }}
          cache: true
      - name: Build
        run: deno task build
      - name: Install FFmpeg
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ffmpeg
          version: "1.0"
      - name: Run integration tests 🧪
        run: deno task test
      - name: Upload integration tests results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-tests-results
          path: |
            integration/__image_snapshots__/*.diff.png
            integration/videos/*.webm
